#!/bin/sh

netdevs () {
    egrep '^[[:space:]]*[[:alnum:]]*:' /proc/net/dev | cut -d: -f1
}

modules () {
    find /lib/modules -type f
}

/bin/mount -t proc none /proc
/bin/mount -t sysfs none /sys
/usr/sbin/setlogcons 5
/sbin/mdev -s
/sbin/ifconfig lo up 127.0.0.1

# Unzip any gzipped modules
for module in `modules` ; do
    if [ "${module%%.gz}" != "${module}" ]; then
	gunzip $module
    fi
done

# Load any modules
for dummy in `modules` ; do
    for module in `modules` ; do
	name=`basename "${module%%.ko}"`
	if ! lsmod | egrep "^$name[[:space:]]" > /dev/null ; then
	    insmod $module
	fi
    done
done

# Apply any static net device configuration from /proc/cmdline
for arg in `cat /proc/cmdline`; do
    if [ "${arg##ip=}" != "${arg}" ]; then
	netdev=`echo "${arg##ip=}" | cut -d: -f6`
	ip=`echo "${arg##ip=}" | cut -d: -f1` \
	    router=`echo "${arg##ip=}" | cut -d: -f3` \
	    subnet=`echo "${arg##ip=}" | cut -d: -f4` \
	    hostname=`echo "${arg##ip=}" | cut -d: -f5` \
	    interface=${netdev} \
	    /usr/share/udhcpc/default.script bound
	while ! ifconfig $netdev | grep RUNNING > /dev/null ; do
	    echo "Waiting for link-up on ${netdev}..."
	    sleep 1
	done
    fi
done

# Bring up any remaining non-loopback net devices using udhcpc
for netdev in `netdevs`; do
    if [ "${netdev}" != "lo" ]; then
	if ! ifconfig $netdev | grep 'inet addr' > /dev/null ; then
	    udhcpc $netdev
	fi
    fi
done
